from os.path import join, abspath, dirname


COL2 = 'REGATDDNRDKGTNKER'
COL9 = 'NDTSSELVTENPSSYKV'
CHANGE_POS = 10

IM2, E2 = COL2[:CHANGE_POS], COL2[CHANGE_POS:]
IM9, E9 = COL9[:CHANGE_POS], COL9[CHANGE_POS:]

RECOMBINANTS = [IM2 + E9, IM9 + E2]

POS_LABELS = ['Im:24', 'Im:26', 'Im:27', 'Im:28', 'Im:29',
              'Im:32', 'Im:33', 'Im:34', 'Im:38', 'Im:58',
              'E:72', 'E:73', 'E:77', 'E:78', 'E:83',
              'E:97', 'E:98']

EXP_PATH = ['REGATDDNRDKGTNKER', 'REGATEDNRDKGTNKER', 'REGASEDNRDKGTNKER', 'REGASEDNRDKATNKER',
            'RDGASEDNRDKATNKER', 'RDGASEDVRDKATNKER', 'RDGASEDVRDKATNKEM', 'NDGASEDVRDKATNKEM',
            'NDGASELVRDKATNKEM', 'NDTASELVRDKATNKEM', 'NDTASELVRDKATNKKM', 'NDTASELVTDKATNKKM',
            'NDTSSELVTDKATNKKM', 'NDTSSELVTDKATNYKM', 'NDTSSELVTEKATNYKM', 'NDTSSELVTEKATSYKM',
            'NDTSSELVTEKATSYKV', 'NDTSSELVTEKASSYKV', 'NDTSSELVTENASSYKV', 'NDTSSELVTENPSSYKV']

BASE_DIR = abspath(join(dirname(__file__), '..'))
DATA_DIR = join(BASE_DIR, 'data')
VIZ_DIR = join(BASE_DIR, 'visualization')
FIGURES_DIR = join(BASE_DIR, 'figures')
ENERGIES_FPATH = join(DATA_DIR, 'colicins.pq')
EXP_DATA_FPATH = join(DATA_DIR, 'experimental_data.csv')
CMAP = 'coolwarm'
